export const defaultOptions = {
  isMulti: false,
  isSearchable: false,
  isDisabled: false,
  styles: {
    container: (styles) => ({
      ...styles,
      // marginRight: "16px",
    }),
    singleValue: (style) => ({
      ...style,
      fontFamily: "Gilroy-Regular",
    }),
    control: (styles) => ({
      ...styles,
      width: "100%",
      outline: "none",
      fontSize: "20px",
      //       marginRight: "20px",
      color: "#3F48CC",
      borderRadius: "0px",
      backgroundColor: "#edeeff",
      border: 0,
      borderRight: "3px solid #3F48CC",
      height: "32px",
      fontFamily: "Gilroy-Regular",
      // border: "1px solid #2A2C35",
      borderColor: "#edeeff",
      boxShadow: "none",
      "&:focus": {
        borderColor: "#edeeff",
        title_img: "",
      },
      "&hover": {
        borderRight: "2px solid #3F48CC",
      },
    }),

    valueContainer: (styles) => ({
      ...styles,
      color: "black",
      padding: "0px!important",
      // marginRight: "100px",
      fontWeight: 500,
      //       display: "flex",
      fontSize: "14px",
      width: "100px",
    }),
    indicatorSeparator: (styles) => ({
      ...styles,
      backgroundColor: "#edeeff",
      with: "0px",
    }),

    indicatorsContainer: (styles) => ({
      ...styles,
      marginRight: "20px",
    }),
    dropdownIndicator: (base) => ({
      ...base,
      color: "#3F48CC",
      padding: "0px",
      //       marginLeft: "5px",
      "&:hover": {
        color: "#2A2C35",
      },
    }),

    placeholder: (styles) => ({
      ...styles,
      color: "#3F48CC",
      fontFamily: "Gilroy-Medium",
      fontSize: "20px",
    }),
  },
};
export const categories = [
  {
    slug: "elektronika",
    id: 1,
    name: "Elektronika",
    img: "/img/elektironika.svg",
    bg: "#FFF9ED",
    marginr: "26px",
    title_img: "/img/elektronika_item.svg",
  },
  {
    slug: "gozallik",
    id: 2,
    name: "Go‘zallik",
    img: "/img/gozallik.svg",
    bg: "#FAEDFF",
    marginr: "26px",
    link: "/gozallik",
    title_img: "",
  },
  {
    slug: "sovgalar",
    id: 3,
    name: "Sovg‘alar",
    img: "/img/sovgalar.svg",
    bg: "#EDFDFF",
    marginr: "26px",
    link: "/sovgalar",
    title_img: "",
  },
  {
    slug: "ayollar-uchun",
    id: 4,
    name: "Ayollar uchun",
    img: "/img/ayollaruchun.svg",
    bg: "#FFF2ED",
    marginr: "26px",
    link: "/ayollar-uchun",
    title_img: "",
  },
  {
    slug: "erkaklar-uchun",
    id: 5,
    name: "Erkaklar uchun",
    img: "/img/erkaklaruchun.svg",
    bg: "#EDFFF1",
    marginr: "26px",
    link: "/erkaklar-uchun",
    title_img: "",
  },
  {
    slug: "bolalar-uchun",
    id: 6,
    name: "Bolalar uchun",
    img: "/img/bolalaruchun.svg",
    bg: "#FFEDFE",
    marginr: "26px",
    link: "/bolalar-uchun",
    title_img: "",
  },
  {
    slug: "avtomobil-uchun",
    id: 7,
    name: "Avtomobil uchun",
    img: "/img/bolalaruchun.svg",
    bg: "#F5FFED",
    marginr: "26px",
    link: "/avtomobil-uchun",
    title_img: "",
  },
  {
    slug: "salomatlik-uchun",
    id: 8,
    name: "Salomatlik uchun",
    img: "/img/bolalaruchun.svg",
    bg: "#EDF3FF",
    marginr: "0px",
    link: "/salomatlik-uchun",
    title_img: "",
  },
];

export const product = [
  { id: 1, name: "Mahsulot", img: "", price: "30000" },
  { id: 2, name: "Mahsulot", img: "", price: "30000" },
  { id: 3, name: "Mahsulot", img: "", price: "30000" },
  { id: 4, name: "Mahsulot", img: "", price: "30000" },
  { id: 5, name: "Mahsulot", img: "", price: "30000" },
  { id: 6, name: "Mahsulot", img: "", price: "30000" },
];
